name: whatsappchat
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:

  photo_view: ^0.14.0
  wakelock_plus: ^1.1.1

  firebase_core: ^3.6.0
  cached_network_image: ^3.3.0
  firebase_messaging: ^15.1.2
  flutter_local_notifications: ^17.2.2
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  archive: ^3.3.0
  path_provider: ^2.0.1
  flutter_staggered_grid_view: ^0.7.0
  local_auth: ^2.1.7
  flutter_spinkit: ^5.2.0
  intl: ^0.18.1
  dio: ^5.4.3+1
  audioplayers: ^6.0.0
  flutter_image_compress: ^2.1.0
  file_picker: ^8.0.3
  image: ^4.0.17
  image_picker: ^1.0.7
  video_compress: ^3.1.2
  path: ^1.9.0
  collection: ^1.17.1
  scrollable_positioned_list: ^0.3.8
  socket_io_client: ^2.0.3
  url_launcher: ^6.1.10
  connectivity_plus: ^6.0.5
  cryptography: ^2.5.0
  encrypt: ^5.0.1
  flutter_secure_storage: ^9.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  uuid: ^4.4.0
  flutter_contacts: ^1.1.9+2
  mobile_scanner: ^3.5.0
  pin_code_fields: ^8.0.1
  cupertino_icons: ^1.0.8
  http: 1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.6
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/chat_bg.png
    - assets/sounds/send.mp3
    - assets/sounds/receive.mp3
    - assets/sounds/delivered.mp3
    - assets/sounds/read.mp3

